// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Character identification AI agent.
 *
 * - identifyCharacters - A function that handles the character identification process.
 * - IdentifyCharactersInput - The input type for the identifyCharacters function.
 * - IdentifyCharactersOutput - The return type for the identifyCharacters function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const IdentifyCharactersInputSchema = z.object({
  text: z.string().describe('The text to identify characters from.'),
});
export type IdentifyCharactersInput = z.infer<typeof IdentifyCharactersInputSchema>;

const IdentifyCharactersOutputSchema = z.object({
  characters: z
    .array(
      z.object({
        name: z.string().describe('The name of the character.'),
        description: z.string().describe('A brief description of the character.'),
      })
    )
    .describe('The list of characters identified in the text.'),
});
export type IdentifyCharactersOutput = z.infer<typeof IdentifyCharactersOutputSchema>;

export async function identifyCharacters(input: IdentifyCharactersInput): Promise<IdentifyCharactersOutput> {
  return identifyCharactersFlow(input);
}

const prompt = ai.definePrompt({
  name: 'identifyCharactersPrompt',
  input: {schema: IdentifyCharactersInputSchema},
  output: {schema: IdentifyCharactersOutputSchema},
  prompt: `You are an expert in identifying characters in a given text.

  Analyze the following text and identify the characters present. For each character, provide a brief description.

  Text: {{{text}}}
  
  If there are no characters, return an empty array.
  `,
});

const identifyCharactersFlow = ai.defineFlow(
  {
    name: 'identifyCharactersFlow',
    inputSchema: IdentifyCharactersInputSchema,
    outputSchema: IdentifyCharactersOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
